version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 20
    commands:
      # Install Docker if needed (for CodeBuild environments that don't have it)
      - nohup /usr/local/bin/dockerd-entrypoint.sh &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      # Install Python and Node dependencies
      - pip install --upgrade pip
      - pip install -r yolo-v5-flask-app/requirements.txt
      - pip install -r depth-anything-flask-app/requirements.txt
      - cd object-detection-react-app && npm ci && cd ..

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      # Add ECR login command here if pushing images

  build:
    commands:
      - echo Building Docker images...
      - docker compose build

  post_build:
    commands:
      - echo Build completed on `date`
      # Add Docker push or deployment steps here if needed

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - '**/.venv/**'
    - '**/node_modules/**'
    - '**/checkpoints/**'
    - '**/*.pth'