version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 20
    commands:
      - nohup /usr/local/bin/dockerd-entrypoint.sh &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - pip install --upgrade pip
      - pip install -r yolo-v5-flask-app/requirements.txt
      - pip install -r depth-anything-flask-app/requirements.txt
      - cd object-detection-react-app && npm ci && cd ..

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - export WEBAPP_API_SERVICE_URL=Mlops-alb-2120823531.us-east-1.elb.amazonaws.com
      - echo "WEBAPP_API_SERVICE_URL=$WEBAPP_API_SERVICE_URL"

  build:
    commands:
      - echo Building Docker images...
      - docker compose build

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - '**/.venv/**'
    - '**/node_modules/**'
    - '**/checkpoints/**'
    - '**/*.pth'
